<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            'academic-list',
            'academic-create',
            'academic-edit',
            'academic-delete',
            'apply-list',
            'apply-create',
            'apply-edit',
            'apply-delete',
            'banner-list',
            'banner-create',
            'banner-edit',
            'banner-delete',
            'campus-list',
            'campus-create',
            'campus-edit',
            'campus-delete',
            'category-list',
            'category-create',
            'category-edit',
            'category-delete',
            'certificate-list',
            'certificate-create',
            'certificate-edit',
            'certificate-delete',
            'contact-list',
            'contact-create',
            'contact-edit',
            'contact-delete',
            'content_group-list',
            'content_group-create',
            'content_group-edit',
            'content_group-delete',
            'content-list',
            'content-create',
            'content-edit',
            'content-delete',
            'event-list',
            'event-create',
            'event-edit',
            'event-delete',
            'feature-list',
            'feature-create',
            'feature-edit',
            'feature-delete',
            'gallery-list',
            'gallery-create',
            'gallery-edit',
            'gallery-delete',
            'group-list',
            'group-create',
            'group-edit',
            'group-delete',
            'history-list',
            'history-create',
            'history-edit',
            'history-delete',
            'how_to_apply-list',
            'how_to_apply-create',
            'how_to_apply-edit',
            'how_to_apply-delete',
            'lecture_skill-list',
            'lecture_skill-create',
            'lecture_skill-edit',
            'lecture_skill-delete',
            'lecture-list',
            'lecture-create',
            'lecture-edit',
            'lecture-delete',
            'menu-list',
            'menu-create',
            'menu-edit',
            'menu-delete',
            'mode-list',
            'mode-create',
            'mode-edit',
            'mode-delete',
            'news-list',
            'news-create',
            'news-edit',
            'news-delete',
            'news_tag-list',
            'news_tag-create',
            'news_tag-edit',
            'news_tag-delete',
            'page-list',
            'page-create',
            'page-edit',
            'page-delete',
            'program-list',
            'program-create',
            'program-edit',
            'program-delete',
            'role-list',
            'role-create',
            'role-edit',
            'role-delete',
            'skill-list',
            'skill-create',
            'skill-edit',
            'skill-delete',
            'slide-list',
            'slide-create',
            'slide-edit',
            'slide-delete',
            'tag-list',
            'tag-create',
            'tag-edit',
            'tag-delete',
            'testimony-list',
            'testimony-create',
            'testimony-edit',
            'testimony-delete',
            'university-list',
            'university-create',
            'university-edit',
            'university-delete'
        ];

        foreach ($permissions as $permission) {
            Permission::create(['name' => $permission]);
        }
    }
}
